spring:
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${OAUTH2_CLIENT_ID}
            clientSecret: ${OAUTH2_CLIENT_SECRET}
jwt:
  key: jimmy1234123412341234123412341234
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
